
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4524',to_date('15-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4525',to_date('16-08-22','dd-mm-yyyy'),'MOVIE_DATABASE_2.sql','C:\Users\junai\OneDrive\Documents\FileUploadDir\MOVIE_DATABASE_2.sql');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4526',to_date('16-08-22','dd-mm-yyyy'),'MOVIE_DATABASE_2.sql','C:\Users\junai\OneDrive\Documents\FileUploadDir\MOVIE_DATABASE_2.sql');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4527',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4528',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4529',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4530',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4531',to_date('16-08-22','dd-mm-yyyy'),'16200058.pdf','C:\Users\junai\OneDrive\Documents\FileUploadDir\16200058.pdf');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4532',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4533',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4534',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4535',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');
insert into DOCUMENT_DETAILS (DOC_ID,CREATED_DATE,FILE_NAME,FILE_LOCATION ) values ('4535',to_date('16-08-22','dd-mm-yyyy'),'insurance.csv','C:\Users\junai\OneDrive\Documents\FileUploadDir\insurance.csv');